# Generated by Django 4.2.6 on 2023-11-09 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CateringSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='catering_sets/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('eventImage', models.ImageField(default='', upload_to='Image/')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=99)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default='0.00', max_length=8)),
                ('fooditemImage', models.ImageField(default='', upload_to='Image/')),
            ],
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=99)),
                ('description', models.CharField(default='', max_length=200)),
                ('categories', models.CharField(choices=[('Breakfast Set', 'Breakfast Set'), ('Lunch Set', 'Lunch Set'), ('Dinner Set', 'Dinner Set')], default='', max_length=99)),
                ('foodmenuImage', models.ImageField(default='', upload_to='Image/')),
                ('featured', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Preparing', 'Preparing'), ('Out of kitchen', 'Out of kitchen'), ('Delivering', 'Delivering'), ('Success', 'Success')], default='Preparing', max_length=99)),
                ('total_price', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_image', models.ImageField(default='', upload_to='Image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('postal', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcateringapp.fooditem')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcateringapp.order')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='foodmenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcateringapp.foodmenu'),
        ),
        migrations.CreateModel(
            name='CateringSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('catering_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='foodcateringapp.cateringset')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcateringapp.fooditem')),
            ],
        ),
        migrations.AddField(
            model_name='cateringset',
            name='items',
            field=models.ManyToManyField(related_name='set_items', through='foodcateringapp.CateringSetItem', to='foodcateringapp.fooditem'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcateringapp.cart')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcateringapp.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField()),
                ('expiry_date', models.DateField()),
                ('cvc', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('additional_info', models.TextField(blank=True)),
                ('catering_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcateringapp.cateringset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
