# Generated by Django 4.2.7 on 2023-11-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcateringapp', '0002_shippingaddress_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='Image/FEGC WHITE.png', upload_to='Image/'),
        ),
    ]
