# Generated by Django 4.2.7 on 2023-11-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tier',
            field=models.CharField(default='Entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
