# Generated by Django 4.2.7 on 2023-11-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
