# Generated by Django 4.2.7 on 2023-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership_level',
            field=models.IntegerField(default=0),
        ),
    ]
