# Generated by Django 4.2.7 on 2023-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_membership_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='membership_level',
            new_name='membership_points',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tier',
            field=models.CharField(default='Entry', max_length=20),
        ),
    ]
