# Generated by Django 4.2.5 on 2023-10-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_foodmenu_number_of_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('food', models.CharField(max_length=99)),
                ('beverage', models.CharField(max_length=99)),
                ('price', models.FloatField(max_length=3)),
            ],
        ),
    ]
